project:
  name: "devops_cicd"
  description: "Generic purposes pipeline for Devops"

repositories:
  - name: "docker_jenkins"
    url: "https://github.com/pjamenaja/docker_jenkins.git"
    credential: ""

jenkins_jobs:
  - name: "jenkins_docker_image_build"
    type: "build" #build|deploy|activation
    branches_include: "master dev/* trunk"
    trigger_period: "1" #minute
    repository: "docker_jenkins"

  - name: "jenkins_docker_image_deploy"
    type: "deploy"
    branches_include: "trunk"
    trigger_period: "2" #minute
    repository: "docker_jenkins"
